[[language]]
name = "c-sharp"
scope = "source.cs"
file-types = ["cs"]
roots = ["*.sln", "*.csproj"]
auto-format = true
language-servers = ["omnisharp"]

[language.formatter]
command = "csharpier"
args = ["--write-stdout"]
