#!/bin/sh

wlr-randr --output DP-3 --mode 3840x2160@120.00 &

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Applications
riverctl map normal Super Return spawn wezterm
riverctl map normal Super s spawn fuzzel

# Clipboard history picker using cliphist + fuzzel
riverctl map normal Super v spawn "sh -c 'cliphist list | fuzzel --dmenu | cliphist decode | wl-copy'"

# Full screen screenshot (Print key)
riverctl map normal None Print spawn 'grim -g "$(slurp)" ~/Pictures/Screenshot-$(date +'%Y-%m-%d-%H%M%S').png | wl-copy'

# Window movement (Vim style)
riverctl map normal Super H focus-view -skip-floating left
riverctl map normal Super J focus-view -skip-floating down
riverctl map normal Super K focus-view -skip-floating up
riverctl map normal Super L focus-view -skip-floating right

# Close window
riverctl map normal Super Q close

# Switch and move between tags
for i in $(seq 1 9); do
    riverctl map normal Super $i set-focused-tags $((1 << ($i - 1)))
    riverctl map normal Super+Shift $i set-view-tags $((1 << ($i - 1)))
done

# Exit river
riverctl map normal Super+Shift E exit

# Volume Control
riverctl map normal None XF86AudioRaiseVolume spawn "pamixer -i 5"
riverctl map normal None XF86AudioLowerVolume spawn "pamixer -d 5"
riverctl map normal None XF86AudioMute spawn "pamixer -t"

# Set wallpaper
swaybg -i ~/dotfiles/wallpapers/oxocarbon.jpg -m fill &

# Dark mode and styling environment variables (INLINE)
export GTK_THEME=Adwaita:dark &
export XCURSOR_THEME=Adwaita &
export XCURSOR_SIZE=24 &
export QT_QPA_PLATFORMTHEME=qt5ct &
export QT_STYLE_OVERRIDE=kvantum &

# Gaps and borders
riverctl border-width 3
riverctl set-cursor-warp on-focus-change
riverctl background-color 0x161616
riverctl border-color-focused 0x33b1ff
riverctl border-color-unfocused 0x282828

# Start background services
~/.config/waybar/watch-waybar.sh &
waybar &
mako &
udiskie --no-notify --tray &
nm-applet &
blueman-applet &
cliphist store &

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &

wl-paste --type text --watch cliphist store &
wl-paste --type image --watch cliphist store &
